#! /usr/bin/env python

from crocs.xparser import xmake
from eacc.lexer import LexError
from eacc.eacc import EaccError
from traceback import print_exc

def regexbuilder():
    regstr  = input('>>> ')
    regtree = xmake(regstr)
    regtree.test()
    regtree.hits()

if __name__ == '__main__':
    while True:
        try:
            regexbuilder()
        except (LexError, EaccError) as e:
            print_exc()